### ISSUE TITLE
Pesq2

### ISSUE THREAD

**Issue by mpariente** [JacobD10/SoundZone_Tools#1]
Hi Jacob, 

Thanks a lot for the Toolbox it looks like a great tool! 
I downloaded it to use stoi.m and pesq.m, the stoi function works great but the PESQ function needs other function to work (set_global, fix_power_level, apply_filter etc...) 

Is there a way to access these functions please? 
I would really appreciate to be able to make it work, 
Thanks in advance

**Comment by mpariente** [comment]
Ok, found these functions there : [https://github.com/Kwapi/NetworksVoIP](url)
Not obvious.. ^^

**Comment by jdonley** [comment]
Hi pianomanu,
The pesq2.m file is written by Yi Hu and Philipos C. Loizou and is available here: http://ecs.utdallas.edu/loizou/speech/composite.zip
I'll add this link to the header for future reference.

I would, however, suggest using pesq_mex_vec.m with pesq_mex_mexw64 as it is much much faster than Loizou's implementation and also faster than a lot of implementations on Mathworks' FileExchange.

~Jacob
