### ISSUE TITLE
SSN error

### ISSUE THREAD

**Issue by ibutera** [JacobD10/SoundZone_Tools#2]
Hi Jacob, 

I came across this helpful code of yours, and I'm trying to use it to create speech shaped noise from a list of words. I can calculate LTASS with no trouble, but I'm getting the following error when I try to run this line: SSN = Tools.ArbitraryOctaveFilt(noise, spect, frqs, Nfft, Fs, OctaveBandSpace);
 
Error using fir2 -> The first frequency must be 0 and the last 1.

The problem seems to be that the variable 'f' isn't calculated properly in line 35 of ArbitraryOctaveFilt, which is... [MAG,f]=Tools.octaveBandMean(SPECT,FREQS,octBandwidth);

'f' should be a vector from 0 to Fs/2. For my file, this should be 44100/2 = 22050. Instead, I'm getting 0:20159, which causes the error shown above in line 40 of ArbitraryOctaveFilt using fir2. 

This issue appears to be specific to my wav file, because I've run this on a sample file from the TIMIT corpus that you reference elsewhere, and as expected, it's error free. Perhaps my sampling rate is the issue? 

Thanks for your help!
iliza

**Comment by jdonley** [comment]
Hi ibutera, I have fixed one issue but there is another where the last octave band may not centre nicely on the Nyquist frequency which causes the normalised frequency vector to limit somewhere just below 1.
This then gives the error you reported.

I will have a think about the best way to get around this issue.

**Comment by jdonley** [comment]
I believe the error would occur when a sampling frequency (fs) is chosen such that (fs/2)/centreFreq is not a power of two. This would mean the Nyquist frequency wouldn't be a centre for a band mean and would be left out of the returned vector.

The fix I've implemented forces a band mean to be found at the Nyquist frequency and includes this in the returned vectors. A warning is displayed if this is the case. 
This fix means the second last and last elements returned will not necessarily be spaced by the octave spacing specified, all other elements will, though.

**Comment by jdonley** [comment]
Test with the following:
```
Fs              = 44100; % Sampling frequency
Nfft            = 1024;  % FFT length
OctaveBandSpace = 1/6;   % 1/6 octave band smoothing
noise;                   % White Gaussian Noise
                         % (or other statistically distributed white spectrum noise)
SpeechFolderOrVector = ... A folder path or vector of speech samples
                  'SpeechFiles\'; 
[spect, frqs] = Tools.LTASS...                 Compute LTASS spectrum
                (SpeechFolderOrVector, Nfft, Fs );
SSN           = Tools.ArbitraryOctaveFilt...   Speech shaped noise
                (noise, spect, frqs, Nfft, Fs, OctaveBandSpace); 

sxx=pwelch(SSN/rms(SSN),rectwin(Nfft),0,Nfft,Fs,'power').^.5;
pl=plot(frqs/1e3,mag2db([spect,sxx]),'linewidth',2);pl(1).Color='r';pl(2).Color='b';
ax=gca;ax.XScale='log';fm=Fs/2/1e3;xlim([0.05 fm]);ax.XTick=[0.1,1,fm];grid on; grid minor;
xlabel('Frequency (kHz)');ylabel('Magnitude (dB)');legend({'LTASS';'SSN'});
```

**Comment by ibutera** [comment]
That works great. Thanks a lot, Jacob!
