### ISSUE TITLE
setup_global not found

### ISSUE THREAD

**Issue by g-aaroncruz** [JacobD10/SoundZone_Tools#4]
Hi Jacob,

I pulled your matlab code but when I try to run it it says that there is no setup_global function available. It seems all the PESQ m files are missing. Help please?

Thanks,
Aaron

**Comment by jdonley** [comment]
Hi Aaron,

The readme suggests that if a file is missing you can check the header of the calling function for a download link. In this case you are calling `pesq2.m` and the function missing is `setup_global()`. This function is available from [the link given in the header](http://ecs.utdallas.edu/loizou/speech/composite.zip) of `pesq2.m`. All the associated files for `pesq2.m` can be found from there as previously mentioned in issue #1.

The PESQ functions which run much faster from the compiled MEX functions are called `pesq_mex_vec.m` and `pesq_mex_fast_vec.m`.

~Jacob
